"""add recovery knowledge

Revision ID: 35abb0c36431
Revises: 4407ed561888
Create Date: 2026-08-29 01:32:38.857436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35abb0c36431'
down_revision: Union[str, Sequence[str], None] = '4407ed561888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=False),
    sa.Column('recommended_action', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_knowledge_items_failure_reason'), 'recovery_knowledge_items', ['failure_reason'], unique=False)
    op.create_index(op.f('ix_recovery_knowledge_items_key'), 'recovery_knowledge_items', ['key'], unique=True)
    op.drop_table('audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.drop_index(op.f('ix_recovery_knowledge_items_key'), table_name='recovery_knowledge_items')
    op.drop_index(op.f('ix_recovery_knowledge_items_failure_reason'), table_name='recovery_knowledge_items')
    op.drop_table('recovery_knowledge_items')
    # ### end Alembic commands ###
