"""add payment details

Revision ID: a0b01e52d61b
Revises: a7aad8961c5a
Create Date: 2026-08-26 00:00:23.812666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b01e52d61b'
down_revision: Union[str, Sequence[str], None] = 'a7aad8961c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('payment_id', sa.String(), nullable=False))
    op.add_column('recovery_cases', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'currency')
    op.drop_column('recovery_cases', 'payment_id')
    # ### end Alembic commands ###
