"""enforce unique payment ids

Revision ID: fd8dcdbbebc0
Revises: a0b01e52d61b
Create Date: 2026-08-26 01:52:18.205083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8dcdbbebc0'
down_revision: Union[str, Sequence[str], None] = 'a0b01e52d61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recovery_cases', ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_cases', type_='unique')
    # ### end Alembic commands ###
